#################################################################
## Main Config
#################################################################

homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_global.yaml

http:
  api_password: !secret http_pws
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_networks: !secret trusted_ip
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key

#################################################################
## Addons
#################################################################

updater:
discovery:
map:
history:
recorder:
logbook:
ios:
sun:
config:
conversation:
tts:
  - platform: google

frontend:
  themes: !include_dir_merge_named themes/

google_assistant:
  project_id: !secret goog_pro_id
  client_id: !secret goog_cli_id
  access_token: !secret goog_token
  api_key: !secret goog_api
  exposed_domains:
    - switch
    - light

shell_command:
  update_ha: "touch /home/pi/.homeassistant/updates/do"


#################################################################
## Bridges
#################################################################

netatmo:
  api_key: !secret neta_api
  secret_key: !secret neta_secret
  username: !secret mail
  password: !secret neta_pws
  discovery: false

#################################################################
## Includes
#################################################################

group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
climate: !include_dir_merge_list climates/
zone: !include zones.yaml
light: !include_dir_merge_list lights/
script: !include_dir_merge_named scripts/
switch: !include_dir_merge_list switches/
binary_sensor: !include_dir_merge_list binary_sensors/
sensor: !include_dir_merge_list sensors/
input_select: !include input_selects.yaml
media_player: !include_dir_merge_list media_player/
history_graph: !include_dir_merge_named history_graphs/
